export class Course {
  id: string = '';
  name: string = '';
  subjectId: string = '';
  subjectName: string = '';
  code: string = '';
  avatar: string = '';
  banner: string = '';
  courseInfo1: string = '';
  courseInfo2: string = '';
  rating: string = '';
  totalRating: string = '';
  totalStudent: string = '';
  price: string = '';
  priceDiscount: string = '';
  promotionTime: string = '';
  createdDate: string = '';
  createdBy: string = '';
  modifiedDate: string = '';
  modifiedBy: string = '';
  shortSummary: string = '';
  isShowHome: string = '';
  teachers: string[] = [];
}
